# Generated by Django 6.0 on 2026-01-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('dessert', 'Dessert'), ('appetizer', 'Appetizer'), ('snack', 'Snack'), ('main', 'Main course'), ('beverage', 'Beverage'), ('salad', 'Salad'), ('soup', 'Soup')], default='main', max_length=20),
        ),
    ]
